import fs from "fs";
import os from "os";
import path from "path";
import { describe, expect, it } from "vitest";
import { runAllDetectors } from "../src/detectors/registry.js";
import { processFixInTempSandbox } from "../src/fixes/patch-engine.js";
import { walkDirectory } from "../src/walker.js";

describe("End-to-End Workflow: Next.js + Supabase + Stripe Fixture Repo", () => {
  it("should scan repo with shared registry, produce findings, apply structured fix, verify in sandbox, and output real diff", async () => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "nantis-e2e-test-"));
    try {
      // Ensure clean test fixture environment inside isolated temp dir
      fs.mkdirSync(path.join(tempDir, "app/api/webhooks/stripe"), { recursive: true });
      fs.mkdirSync(path.join(tempDir, "supabase/migrations"), { recursive: true });

      fs.writeFileSync(
        path.join(tempDir, "package.json"),
        JSON.stringify(
          {
            name: "nextjs-supabase-stripe-app",
            version: "1.0.0",
            dependencies: {
              next: "14.2.0",
              axios: "0.21.1",
              stripe: "12.0.0",
              "@supabase/supabase-js": "2.0.0",
            },
          },
          null,
          2
        ),
        "utf-8"
      );

      fs.writeFileSync(
        path.join(tempDir, "app/api/webhooks/stripe/route.ts"),
        'import { stripe } from "@/lib/stripe";\nexport async function POST(req) {\n  const body = await req.json();\n  return new Response("OK");\n}\n',
        "utf-8"
      );

      fs.writeFileSync(
        path.join(tempDir, "supabase/migrations/20260101_init.sql"),
        "CREATE TABLE public.invoices (id uuid PRIMARY KEY, user_id uuid, amount integer);\n",
        "utf-8"
      );

      // 1. Walk repository and build filesMap
      const files = walkDirectory(tempDir);
      const filesMap = new Map<string, string>();
      for (const f of files) {
        filesMap.set(f.relativePath, f.content);
      }

      // 2. Scan using shared detector registry
      const findings = await runAllDetectors(filesMap, {
        targetFolder: tempDir,
        offlineMode: true,
      });

      expect(findings.length).toBeGreaterThan(0);

      // Verify specific expected real findings are produced
      const rlsFinding = findings.find((f) => f.ruleId === "missing-rls-in-migration");
      const stripeWebhookFinding = findings.find((f) => f.ruleId === "stripe-webhook-no-signature");

      expect(
        rlsFinding,
        "End-to-End Test Failed: Expected 'missing-rls-in-migration' finding from scan"
      ).toBeDefined();

      expect(
        stripeWebhookFinding,
        "End-to-End Test Failed: Expected 'stripe-webhook-no-signature' finding from scan"
      ).toBeDefined();

      // 3. Apply fix in isolated temp sandbox using patch engine
      const targetFinding = rlsFinding!;
      const { fixResult, snapshot } = await processFixInTempSandbox(
        tempDir,
        filesMap,
        targetFinding,
        undefined,
        { initialFindings: findings }
      );

      // 4. Assert fix engine succeeded with automated kind
      expect(
        fixResult.kind,
        `End-to-End Fix Failed: Expected automated fix kind, received '${fixResult.kind}'`
      ).toBe("automated");

      if (fixResult.kind === "automated") {
        // 5. Assert verification passed in sandbox
        expect(
          fixResult.verificationReport.passed,
          `End-to-End Sandbox Verification Failed: ${fixResult.verificationReport.dropReason}`
        ).toBe(true);

        // 6. Assert real diff was generated by comparing before and after content
        expect(fixResult.diff).toContain("--- a/supabase/migrations/20260101_init.sql");
        expect(fixResult.diff).toContain("+++ b/supabase/migrations/20260101_init.sql");
        expect(fixResult.diff).toContain("+ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;");
        expect(fixResult.diff).toContain('+CREATE POLICY "Tenant access policy" ON invoices FOR ALL USING (auth.uid() = user_id);');

        // Console output showing real generated diff for verification
        console.log("\n================ REAL E2E VERIFIED FIX DIFF ================\n");
        console.log(fixResult.diff);
        console.log("\n============================================================\n");
      }

      expect(snapshot.files.size).toBeGreaterThan(0);
    } finally {
      try {
        fs.rmSync(tempDir, { recursive: true, force: true });
      } catch {
        // Ignore cleanup errors
      }
    }
  }, 30000);
});
